### ISSUE TITLE
Widok szczegółów jednego studenta

### ISSUE THREAD

**Issue by marcinkunert** [javastartpl/zadanka#24]
Przykładowy link:

http://localhost:8080/kursanci/1 powinien wyświetlać dane kursanta o identyfikatorze 1.

W przyszłości w ramach tego widoku będą wyświetlane wszystkie zadania studenta. Powstanie do tego osobne zadanie.

**Comment by Matheus2168** [comment]
ID powinno być liczbowe, czy może być np. J-Kowalski ?

**Comment by marcinkunert** [comment]
@Matheus2168 powinno być liczbowe, najlepiej typ `long`
